Master
M-Khairy-B/Protfolio-Main pull request #1
Opened 2024-07-22 11:22 UTC by M-Khairy-B

2024-07-22 12:07 UTC, mukhtar-ali requested changes

2024-07-22 12:07 UTC, mukhtar-ali commented on src/template/partials/header.html
> +    <div class="container p-0">
Missing header tag!

2024-07-22 12:07 UTC, mukhtar-ali commented on src/template/partials/header.html
> +    <div class="container p-0">
We agreed that we never do styles to container, row and columns. 
Why are you removing the padding here?

2024-07-22 12:07 UTC, mukhtar-ali commented on src/template/partials/header.html
> +    <div class="container p-0">
Alignment issue

2024-07-22 12:07 UTC, mukhtar-ali commented on src/template/partials/header.html
> +                </div>
Space between the icon and button not like the design, that's due to the icon has extra space inside.

2024-07-22 12:07 UTC, mukhtar-ali commented on src/pages/index.html
> +                                <i class="fa-solid fa-location-dot"></i>
Icon not like the design!!

2024-07-22 12:07 UTC, mukhtar-ali commented on src/pages/index.html
> +                            </div>
Both are not like the design in terms of spacing between icons and text

2024-07-22 12:07 UTC, mukhtar-ali commented on src/pages/index.html
> +                        </div>
Icons are not like the design

2024-07-22 12:07 UTC, mukhtar-ali commented on src/pages/index.html
> +                            <div class="wrapper-gray"></div>
It's best practices to make the gray box with after or before

2024-07-22 12:07 UTC, mukhtar-ali commented on src/pages/index.html
> +                        <h2>Curious about me? Here you have it:</h2>
This should be h3 instead as you have h2 already inside the section

2024-07-22 12:07 UTC, mukhtar-ali commented on src/template/component/card.html
> +</div>
You should keep the grid details outside of the component, Imagine using the same component in a different place with another grid setup.

2024-07-22 12:07 UTC, mukhtar-ali commented on src/template/component/card.html
> +                </ul>
Not aligned like the design

2024-07-22 12:07 UTC, mukhtar-ali commented on src/template/component/card.html
> +    </div>
Missing background color

2024-07-22 12:07 UTC, mukhtar-ali commented on src/pages/index.html
> +            </div>
Why you didn't use the macro you created?

2024-07-22 12:07 UTC, mukhtar-ali commented on src/pages/index.html
> +                        />
Not like the design

2024-07-22 12:07 UTC, mukhtar-ali commented on src/pages/index.html
> +                            <h4>Fiskil</h4>
h3

2024-07-22 12:07 UTC, mukhtar-ali commented on src/pages/index.html
> +                                    src="assets/images/Icon Button.svg"
use small letter in all of your naming convention

2024-07-22 12:07 UTC, mukhtar-ali commented on src/pages/index.html
> +                    <div class="details-project">
Missing box shadow

2024-07-22 12:07 UTC, mukhtar-ali commented on src/pages/index.html
> +                    <div class="card-testimonials">
background color is missing

2024-07-22 12:07 UTC, mukhtar-ali commented on src/pages/index.html
> +                    <div class="card-testimonials">
insider space not like the design.

2024-07-22 12:07 UTC, mukhtar-ali commented on src/template/partials/footer.html
> +                        </div>
Not like the design

2024-07-22 12:07 UTC, mukhtar-ali commented on src/template/partials/footer.html
> +                        </div>
Icons?

2024-07-22 12:15 UTC, M-Khairy-B commented on src/template/partials/header.html
> +    <div class="container p-0">
Done

2024-07-22 12:25 UTC, M-Khairy-B commented on src/template/partials/header.html
> +                </div>
Done

2024-07-22 12:41 UTC, M-Khairy-B commented on src/pages/index.html
> +                                <i class="fa-solid fa-location-dot"></i>
Done

2024-07-22 12:42 UTC, M-Khairy-B commented on src/pages/index.html
> +                            </div>
Done

2024-07-22 12:47 UTC, M-Khairy-B commented on src/pages/index.html
> +                        </div>
Done

2024-07-22 12:51 UTC, M-Khairy-B commented on src/pages/index.html
> +                            <div class="wrapper-gray"></div>
Done

2024-07-22 12:51 UTC, M-Khairy-B commented on src/template/partials/header.html
> +    <div class="container p-0">
Done

2024-07-22 12:51 UTC, M-Khairy-B commented on src/template/partials/header.html
> +    <div class="container p-0">
Done

2024-07-22 12:52 UTC, M-Khairy-B commented on src/pages/index.html
> +                        <h2>Curious about me? Here you have it:</h2>
Done

2024-07-22 12:55 UTC, M-Khairy-B commented on src/template/component/card.html
> +    </div>
Done

2024-07-22 13:00 UTC, M-Khairy-B commented on src/template/component/card.html
> +</div>
ok

2024-07-22 13:04 UTC, M-Khairy-B commented on src/template/component/card.html
> +                </ul>
Done

2024-07-22 13:06 UTC, M-Khairy-B commented on src/pages/index.html
> +                        />
Done

2024-07-22 13:08 UTC, M-Khairy-B commented on src/pages/index.html
> +                            <h4>Fiskil</h4>
Done

2024-07-22 13:10 UTC, M-Khairy-B commented on src/pages/index.html
> +                    <div class="details-project">
Done

2024-07-22 13:13 UTC, M-Khairy-B commented on src/pages/index.html
> +                    <div class="card-testimonials">
Done

2024-07-22 13:16 UTC, M-Khairy-B commented on src/pages/index.html
> +                    <div class="card-testimonials">
Done

2024-07-22 13:18 UTC, M-Khairy-B commented on src/template/partials/footer.html
> +                        </div>
Done

2024-07-22 13:34 UTC, M-Khairy-B commented on src/template/partials/footer.html
> +                        </div>
Done

2024-07-23 09:37 UTC, Ahmed-Hassan-96 commented on src/template/partials/header.html
> +                </div>
margin to parent not to button

2024-07-23 09:37 UTC, Ahmed-Hassan-96 commented on src/pages/index.html
> +                                <i class="fa-solid fa-location-dot"></i>
not done 
Where is the icon ?

2024-07-23 09:38 UTC, Ahmed-Hassan-96 commented on src/pages/index.html
> +                            </div>
not done
Same

2024-07-23 09:44 UTC, Ahmed-Hassan-96 commented on src/pages/index.html
> +                        </div>
Not done

2024-07-23 09:45 UTC, Ahmed-Hassan-96 commented on src/pages/index.html
> +                            <div class="wrapper-gray"></div>
not done where is the grey background

2024-07-23 09:51 UTC, Ahmed-Hassan-96 commented on src/template/component/card.html
> +</div>
Not done

2024-07-23 09:51 UTC, Ahmed-Hassan-96 commented on src/template/component/card.html
> +                </ul>
not done

2024-07-23 09:53 UTC, Ahmed-Hassan-96 commented on src/pages/index.html
> +            </div>
not done

2024-07-23 09:54 UTC, Ahmed-Hassan-96 commented on src/pages/index.html
> +                        />
not done

2024-07-23 09:55 UTC, Ahmed-Hassan-96 commented on src/pages/index.html
> +                    <div class="details-project">
not done

2024-07-23 09:56 UTC, Ahmed-Hassan-96 commented on src/pages/index.html
> +                    <div class="card-testimonials">
not done

2024-07-23 09:56 UTC, Ahmed-Hassan-96 commented on src/template/partials/footer.html
> +                        </div>
not done

2024-07-23 10:05 UTC, M-Khairy-B commented on src/pages/index.html
> +                                <i class="fa-solid fa-location-dot"></i>
I was wrong src

2024-07-23 11:06 UTC, M-Khairy-B commented on src/pages/index.html
> +                        </div>
Done

2024-07-23 11:07 UTC, M-Khairy-B commented on src/pages/index.html
> +                                <i class="fa-solid fa-location-dot"></i>
Done

2024-07-23 11:09 UTC, M-Khairy-B commented on src/pages/index.html
> +                            <div class="wrapper-gray"></div>
Done 
وربنا معملوله

2024-07-23 11:10 UTC, M-Khairy-B commented on src/template/component/card.html
> +</div>
I don't do it macron

2024-07-23 11:12 UTC, M-Khairy-B commented on src/pages/index.html
> +            </div>
I don't do it macron
he said Mukhtar

2024-07-23 11:18 UTC, M-Khairy-B commented on src/pages/index.html
> +                            </div>
I swear to God 
same Almost a figma

2024-07-23 11:22 UTC, M-Khairy-B commented on src/template/partials/footer.html
> +                        </div>
I want to know the reason ?

2024-07-23 11:34 UTC, M-Khairy-B commented on src/pages/index.html
> +                    <div class="details-project">
Done

2024-07-23 11:36 UTC, M-Khairy-B commented on src/pages/index.html
> +                        />
the img make box shadow

2024-07-23 11:49 UTC, M-Khairy-B commented on src/template/partials/header.html
> +                </div>
Done

2024-09-25 14:27 UTC, closed without merging